---
services:
    aiworker:
        build: ./aiworker # see Dockerfile below
        network_mode: host # UDP sockets
        environment:
            - WHISPER_URL=http://192.168.68.137:8080
            - OLLAMA_URL=http://192.168.68.137:11434/v1/chat/completions
            - KOKORO_URL=http://192.168.68.134:8880
        restart: unless-stopped
