[global]
endpoint_identifier_order = ip,username,anonymous

; ===== trunk to Callcentric =========
[callcentric]
 type=registration
 transport=transport-udp
 retry_interval=60
 contact_user=17735414239
 outbound_auth=callcentric-auth
 server_uri=sip:sip.callcentric.com
 client_uri=sip:17735414239@callcentric.com

[callcentric-auth]
 type=auth
 auth_type=userpass
 username=17778546416
 password=8%ZSCNTf7$e7#v9FBve!uu7w4qM

[callcentric-endpoint]
 type=endpoint
 transport=transport-udp
 context=from-pstn
 outauth=callcentric-auth
 aors=callcentric-aor
 disallow=all
 allow=ulaw,alaw

[callcentric-aor]
 type=aor
 contact=sip:callcentric.com

; ===== local loop to AI worker =====
[ai]
 type=endpoint
 aors=ai-aor
 context=from-ai
 disallow=all
 allow=slin16

[ai-aor]
 type=aor
 max_contacts=1

[transport-udp]
 type=transport
 protocol=udp
 bind=0.0.0.0:5060
 external_media_address=68.45.110.215
 external_signaling_address=68.45.110.215
