; ---------- templates ----------
[_nat](!)
endpoint/rewrite_contact           = yes
endpoint/rtp_symmetric             = yes
endpoint/direct_media              = no
endpoint/bind_rtp_to_media_address = yes

[_qos](!)
endpoint/tos_audio = ef
endpoint/tos_video = af41

; ---------- Callcentric ----------
[callcentric](!,template=_nat,_qos)
type                    = wizard
sends_registrations     = yes
remote_hosts            = sip.callcentric.net
outbound_auth/username  = 17778546416
outbound_auth/password  = 8%ZSCNTf7$e7#v9FBve!uu7w4qM
endpoint/from_user      = 17778546416
endpoint/from_domain    = sip.callcentric.net
endpoint/allow          = !all,ulaw
identify/endpoint       = callcentric
identify/match          = 199.87.144.0/21
identify/match          = 204.11.192.0/22
transport/udp/external_signaling_address =  68.45.110.215
transport/udp/external_media_address     = 68.45.110.215

; ---------- local phone ----------
[1000](!,template=_nat,_qos)
type                = wizard
accepts_registrations = yes
inbound_auth/username = 100
inbound_auth/password = 8%ZSCNTf7$e7#v9FBve!uu7w4qM
endpoint/context      = from-internal
endpoint/allow        = !all,ulaw
