import fs from 'node:fs/promises'
import fsSync from 'node:fs'
import path from 'node:path'
import {
  EngineSecretSource,
  GetSipSettingsResponse,
  RestartSipResponse,
  SipRuntimeStatus,
  SipSecretStatusMap,
  SipSettings,
  SipSettingsSchema,
  UpdateSipSettingsRequest,
  UpdateSipSettingsRequestSchema,
} from '../../../shared/src/index.js'
import { config } from '../config.js'
import { HttpError } from '../lib/errors.js'
import { sipSecretRepository } from '../repositories/sipSecretRepository.js'
import { sipSettingsRepository } from '../repositories/sipSettingsRepository.js'
import { TelephonyGatewayService } from './telephonyGatewayService.js'

function quoteBaresipValue(value: string): string {
  if (/[\r\n]/.test(value)) {
    throw new HttpError(400, 'SIP account values cannot contain line breaks.')
  }

  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

export function renderBaresipAccountLine(
  settings: SipSettings,
  authPassword: string
): string {
  const value = SipSettingsSchema.parse(settings)
  if (!value.enabled || !value.accountUri) {
    throw new HttpError(400, 'SIP account settings are not enabled.')
  }

  if (!authPassword.trim()) {
    throw new HttpError(400, 'SIP auth password is required.')
  }

  const options = [
    value.authUsername ? `auth_user=${quoteBaresipValue(value.authUsername)}` : null,
    `auth_pass=${quoteBaresipValue(authPassword.trim())}`,
    value.outboundProxy
      ? `outbound=${quoteBaresipValue(value.outboundProxy)}`
      : null,
    'answermode=auto',
    `regint=${value.registrationInterval}`,
    value.preferredCodecs.length > 0
      ? `audio_codecs=${value.preferredCodecs.join(',')}`
      : null,
  ].filter(Boolean)

  return `${quoteBaresipValue(value.accountLabel)} <${value.accountUri}>;${options.join(';')}`
}

export function renderBaresipAccountsFile(
  settings: SipSettings,
  authPassword: string | null
): string {
  const header = [
    '# Generated by ComFlow admin settings.',
    '# Do not edit by hand; changes may be overwritten.',
  ]

  if (!settings.enabled) {
    return [...header, '# SIP account disabled.', ''].join('\n')
  }

  if (!authPassword) {
    throw new HttpError(
      400,
      'SIP auth password is required when SIP is enabled.'
    )
  }

  return [
    ...header,
    `# account_label=${settings.accountLabel}`,
    renderBaresipAccountLine(settings, authPassword),
    '',
  ].join('\n')
}

export class BaresipManagementService {
  constructor(private readonly telephonyGateway: TelephonyGatewayService) {}

  async getSettingsResponse(): Promise<GetSipSettingsResponse> {
    return {
      settings: this.getCurrentSettings(),
      secrets: this.getSecretStatuses(),
      status: await this.getStatus(),
    }
  }

  async updateSettings(
    input: UpdateSipSettingsRequest
  ): Promise<GetSipSettingsResponse> {
    const { settings, secrets } = UpdateSipSettingsRequestSchema.parse(input)
    const authPassword = this.getEffectivePasswordAfterPatch(secrets)

    renderBaresipAccountsFile(settings, authPassword)
    sipSettingsRepository.upsert(settings)
    if (secrets) {
      sipSecretRepository.applyPatch(secrets)
    }
    await this.writeAccountsFile(settings, authPassword)

    return this.getSettingsResponse()
  }

  async restart(): Promise<RestartSipResponse> {
    const settings = this.getCurrentSettings()
    const authPassword = this.getEffectivePassword()
    await this.writeAccountsFile(settings, authPassword)

    if (!config.telephony.baresipRestartUrl) {
      return {
        ok: false,
        supported: false,
        message:
          'Baresip accounts were written, but runtime restart is not configured. Restart the baresip service/container or set COMFLOW_BARESIP_RESTART_URL to a supervisor endpoint.',
        status: await this.getStatus(),
      }
    }

    const response = await fetch(config.telephony.baresipRestartUrl, {
      method: 'POST',
    })

    if (!response.ok) {
      throw new HttpError(
        502,
        `Baresip restart supervisor returned ${response.status}.`
      )
    }

    return {
      ok: true,
      supported: true,
      message: 'Baresip restart requested.',
      status: await this.getStatus(),
    }
  }

  async getStatus(): Promise<SipRuntimeStatus> {
    return {
      telephonyMode: config.telephony.mode === 'baresip' ? 'baresip' : 'fake',
      controlHost: config.telephony.baresipCtrlHost,
      controlPort: config.telephony.baresipCtrlPort,
      controlConnected: this.telephonyGateway.isConnected(),
      accountsPath: config.telephony.baresipAccountsPath,
      accountsLastWrittenAt: this.getAccountsLastWrittenAt(),
      restartSupported: Boolean(config.telephony.baresipRestartUrl),
      restartMechanism: config.telephony.baresipRestartUrl
        ? 'supervisor'
        : 'unavailable',
    }
  }

  getCurrentSettings(): SipSettings {
    return SipSettingsSchema.parse(
      sipSettingsRepository.get() ?? config.defaultSipSettings
    )
  }

  getOutboundDialingDomain(): string | null {
    const settings = this.getCurrentSettings()
    if (settings.enabled && settings.outboundDialingDomain) {
      return settings.outboundDialingDomain
    }

    return config.telephony.sipOutboundDomain
  }

  private async writeAccountsFile(
    settings: SipSettings,
    authPassword: string | null
  ) {
    const content = renderBaresipAccountsFile(settings, authPassword)
    const accountsPath = config.telephony.baresipAccountsPath
    const directory = path.dirname(accountsPath)
    const tempPath = path.join(
      directory,
      `.${path.basename(accountsPath)}.${process.pid}.${Date.now()}.tmp`
    )

    await fs.mkdir(directory, { recursive: true })
    try {
      await fs.writeFile(tempPath, content, { mode: 0o600 })
      await fs.rename(tempPath, accountsPath)
    } finally {
      await fs.unlink(tempPath).catch(() => undefined)
    }
  }

  private getEffectivePassword(): string | null {
    return (
      sipSecretRepository.getAuthPassword() ??
      config.secrets.sipAuthPassword ??
      null
    )
  }

  private getEffectivePasswordAfterPatch(
    patch: UpdateSipSettingsRequest['secrets'] | undefined
  ): string | null {
    if (patch?.authPassword !== undefined) {
      return patch.authPassword ?? config.secrets.sipAuthPassword ?? null
    }

    return this.getEffectivePassword()
  }

  private getSecretStatuses(): SipSecretStatusMap {
    const storedValue = sipSecretRepository.getAuthPassword()
    const source: EngineSecretSource = storedValue
      ? 'stored'
      : config.secrets.sipAuthPassword
        ? 'env'
        : 'missing'

    return {
      authPassword: {
        configured: source !== 'missing',
        source,
      },
    }
  }

  private getAccountsLastWrittenAt(): string | null {
    try {
      return fsSync
        .statSync(config.telephony.baresipAccountsPath)
        .mtime.toISOString()
    } catch {
      return null
    }
  }
}
